version = "2"

environment = ["MY_ENV", "NODE_ENV"]
project = "227f4033-fdbb-482b-847c-b06600dc8e69"

[override]
FORCE_COLOR = "1"


[cache]
path = "./node_modules/.cache/"


[profile.development]
project = "227f4033-fdbb-482b-847c-b06600dc8e69"

[profile.development.override]
FORCE_COLOR = "1"
TEST_ENVIRONMENT_VARIABLE = "some value"
OPENAI_API_KEY = "more values"


[profile.production]
project = "227f4033-fdbb-482b-847c-b06600dc8e69"
